version: '3.7'

services:
  redis:
    image: "redis:alpine"
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    labels:
      GLOBAL_NAME: redis
    networks:
      - chassis
    dns: 172.30.30.30

networks:
  chassis:
    external: true
