global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.
scrape_configs:

  # Scrape all HTTP APIs that we host
  - job_name: 'consul-webapi'
    consul_sd_configs:
      - server: 'consul-8500.service.consul:8500'
        scheme: http
        tags:
          - 'webapi'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: service
  - job_name: traefik
    consul_sd_configs:
      - server: 'consul-8500.service.consul:8500'
        scheme: http
        tags:
          - 'traefikmetrics'
