version: '3.7'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector
      environment:
        SPAN_STORAGE_TYPE: elasticsearch
        ES_SERVER_URLS: http://elasticsearch:9200
      ports:
        - "14269"
        - "14268:14268"
        - "14250"
        - "9411:9411"
      restart: on-failure
      depends_on:
        - elasticsearch
      networks:
        - chassis
      labels:
        traefik.enable: false

    jaeger-query:
      image: jaegertracing/jaeger-query
      environment:
        SPAN_STORAGE_TYPE: elasticsearch
        ES_SERVER_URLS: http://elasticsearch:9200
        JAEGER_ENDPOINT: http://jaeger-collector:14268/api/traces
      ports:
        - "16686:16686"
        - "16687"
      restart: on-failure
      depends_on:
        - elasticsearch
      networks:
        - chassis
      labels:
        traefik.enable: false

    jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
      depends_on:
        - jaeger-collector
      networks:
        - chassis
      labels:
        traefik.enable: false

    elasticsearch:
      image: elasticsearch:7.7.1
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        discovery.type: single-node
      networks:
        - chassis
      labels:
        traefik.enable: false
      deploy:
        resources:
          limits:
            memory: 1024M
      ulimits:
        memlock:
          soft: -1
          hard: -1

networks:
  chassis:
    external: true
